language: csharp

mono: none

dotnet: 5.0

before_install:
- sudo apt-get -y install libpam0g-dev

install:
- dotnet restore

script:
- dotnet build -c Release

before_deploy:
- dotnet pack -c Release
- ls ./

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: dotnet nuget push ./src/Appwrite/bin/Release/Appwrite.*.nupkg  -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
#  on:
#    tags: true
